stages:
  - sonar 
  - build

build:js:
  image: node:latest
  stage: build
  script:
    - yarn install
    - yarn prod
    - cat public/mix-manifest.json # See asset versions in the build log
  artifacts:
    expire_in: 1 week
    paths:
      - public
  
variables:
  SONAR_USER_HOME: "./.sonar"  
  GIT_DEPTH: "0"
sonarcloud-check:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    sonar-scanner.bat -D"sonar.projectKey=qws-cicd" -D"sonar.sources=." -D"sonar.host.url=https://192.168.100.72" -D"sonar.login=1876e0696a874b865cf7697d2f837d68d84ff5b0"
  only:
    - merge_requests
    - master
    - develop





